// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbKqqmagMQFKNPL4NUIEYehlEaICBmztY',
    appId: '1:864875416897:web:9dc077828aa2961fa0a5c0',
    messagingSenderId: '864875416897',
    projectId: 'socially-d0cbb',
    authDomain: 'socially-d0cbb.firebaseapp.com',
    storageBucket: 'socially-d0cbb.firebasestorage.app',
    measurementId: 'G-H7BF7GD0JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX6xjAWGqwzzo7fTu6xkd-OrNWo6DxTQM',
    appId: '1:864875416897:android:3ce2ffa11a91ee92a0a5c0',
    messagingSenderId: '864875416897',
    projectId: 'socially-d0cbb',
    storageBucket: 'socially-d0cbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcH1Q4mn373qxHnEJqBFYvCXlVExkjJxA',
    appId: '1:864875416897:ios:690aa3fa311641a5a0a5c0',
    messagingSenderId: '864875416897',
    projectId: 'socially-d0cbb',
    storageBucket: 'socially-d0cbb.firebasestorage.app',
    iosBundleId: 'com.example.socially',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcH1Q4mn373qxHnEJqBFYvCXlVExkjJxA',
    appId: '1:864875416897:ios:690aa3fa311641a5a0a5c0',
    messagingSenderId: '864875416897',
    projectId: 'socially-d0cbb',
    storageBucket: 'socially-d0cbb.firebasestorage.app',
    iosBundleId: 'com.example.socially',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbKqqmagMQFKNPL4NUIEYehlEaICBmztY',
    appId: '1:864875416897:web:8e246117c649e0e4a0a5c0',
    messagingSenderId: '864875416897',
    projectId: 'socially-d0cbb',
    authDomain: 'socially-d0cbb.firebaseapp.com',
    storageBucket: 'socially-d0cbb.firebasestorage.app',
    measurementId: 'G-03PY0EQLYM',
  );
}
